import { access, copyFile, mkdir, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { homedir } from "node:os";
import { fileURLToPath } from "node:url";
import packageJson from "../../../package.json" with { type: "json" };

import type { OpenClawExtensionRuntimeConfig } from "./extension/runtime.js";

export type OpenClawExtensionCommandOptions = {
  local?: boolean;
  runtimeConfig?: OpenClawExtensionRuntimeConfig;
};

export type InstallOpenClawExtensionResult = {
  extensionDir: string;
  configPath: string;
  extensionBackupPath?: string;
  configBackupPath?: string;
  configUpdated: boolean;
};

export type UninstallOpenClawExtensionResult = {
  extensionDir: string;
  configPath: string;
  removedDir: boolean;
  removedConfigEntries: number;
  configBackupPath?: string;
};

export type OpenClawDoctorReport = {
  extensionDir: string;
  configPath: string;
  status: "ok" | "warn" | "broken" | "disabled";
  issues: string[];
  fixCommand: string;
  checkedPaths: string[];
  missingPaths: string[];
};

const TOKENJUICE_OPENCLAW_PLUGIN_ID = "tokenjuice-openclaw";
const TOKENJUICE_OPENCLAW_FIX_COMMAND = "tokenjuice install openclaw";
const TOKENJUICE_OPENCLAW_MANIFEST_NAME = TOKENJUICE_OPENCLAW_PLUGIN_ID;
const TOKENJUICE_OPENCLAW_MANIFEST_DESCRIPTION = "tokenjuice host adapter for OpenClaw: compacts bash (exec) tool output before it enters the agent transcript, using OpenClaw's synchronous tool_result_persist hook.";

function getOpenClawConfigPath(): string {
  return process.env.OPENCLAW_CONFIG_PATH || join(homedir(), ".openclaw", "openclaw.json");
}

function getDefaultWorkspaceDir(): string {
  return join(homedir(), ".openclaw", "workspace");
}

function getExtensionDir(workspaceDir: string): string {
  return join(workspaceDir, ".openclaw", "extensions", TOKENJUICE_OPENCLAW_PLUGIN_ID);
}

async function writeAtomically(path: string, content: string): Promise<void> {
  const tempPath = `${path}.tmp`;
  await writeFile(tempPath, content, "utf8");
  await rename(tempPath, path);
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

async function resolveRuntimeEntryPoint(): Promise<string> {
  const candidates = [
    fileURLToPath(new URL("./extension/runtime.ts", import.meta.url)),
    fileURLToPath(new URL("../../../src/hosts/openclaw/extension/runtime.ts", import.meta.url)),
  ];
  for (const candidate of candidates) {
    try {
      await access(candidate);
      return candidate;
    } catch {
      continue;
    }
  }
  throw new Error(
    `unable to resolve openclaw runtime source entrypoint from ${candidates.join(", ")}`,
  );
}

async function bundleOpenClawRuntimeSource(): Promise<string> {
  let esbuild;
  try {
    esbuild = await import("esbuild");
  } catch (error) {
    throw new Error(`unable to load esbuild to bundle the openclaw runtime: ${String(error)}`);
  }

  const entryPoint = await resolveRuntimeEntryPoint();
  const result = await esbuild.build({
    entryPoints: [entryPoint],
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node20",
    write: false,
  });

  const runtimeSource = result.outputFiles[0]?.text;
  if (!runtimeSource) {
    throw new Error("failed to bundle the openclaw runtime: esbuild produced no output");
  }
  return runtimeSource;
}

async function loadOpenClawRuntimeSource(local: boolean): Promise<string> {
  if (local) {
    return await bundleOpenClawRuntimeSource();
  }

  const runtimeAssetUrl = new URL("./extension/runtime.js", import.meta.url);
  try {
    return await readFile(runtimeAssetUrl, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
      throw error;
    }
  }
  return await bundleOpenClawRuntimeSource();
}

function buildExtensionEntrySource(
  runtimeSource: string,
  runtimeConfig: OpenClawExtensionRuntimeConfig,
): string {
  return String.raw`/**
 * tokenjuice openclaw extension entry point
 * generated by tokenjuice v${packageJson.version}
 */

${runtimeSource}

const config = ${JSON.stringify(runtimeConfig, null, 2)};

export default function register(api) {
  return createTokenjuiceOpenClawExtension(config)(api);
}
`;
}

function buildPackageJson(): string {
  return `${JSON.stringify(
    {
      name: TOKENJUICE_OPENCLAW_MANIFEST_NAME,
      version: packageJson.version,
      private: true,
      description: TOKENJUICE_OPENCLAW_MANIFEST_DESCRIPTION,
      openclaw: {
        extensions: ["./index.js"],
      },
    },
    null,
    2,
  )}\n`;
}

function buildOpenClawPluginManifest(): string {
  return `${JSON.stringify(
    {
      id: TOKENJUICE_OPENCLAW_PLUGIN_ID,
      name: "Tokenjuice",
      description: TOKENJUICE_OPENCLAW_MANIFEST_DESCRIPTION,
      configSchema: {
        type: "object",
        additionalProperties: false,
        properties: {
          toolName: { type: "string", minLength: 1 },
          maxInlineChars: { type: "number", minimum: 1 },
          commandCaptureTtlMs: { type: "number", minimum: 1 },
          maxPendingCommands: { type: "number", minimum: 1 },
        },
      },
    },
    null,
    2,
  )}\n`;
}

async function readOpenClawConfig(configPath: string): Promise<{ data: Record<string, unknown>; existed: boolean; raw?: string }> {
  try {
    const raw = await readFile(configPath, "utf8");
    const parsed = JSON.parse(raw) as unknown;
    if (!isRecord(parsed)) {
      return { data: {}, existed: true, raw };
    }
    return { data: parsed, existed: true, raw };
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return { data: {}, existed: false };
    }
    throw new Error(`failed to read openclaw config at ${configPath}: ${error instanceof Error ? error.message : String(error)}`);
  }
}

function getWorkspaceDirFromConfig(config: Record<string, unknown>): string | undefined {
  const agents = config.agents;
  if (!isRecord(agents)) {
    return undefined;
  }
  const defaults = agents.defaults;
  if (!isRecord(defaults)) {
    return undefined;
  }
  const workspace = defaults.workspace;
  if (typeof workspace !== "string" || !workspace) {
    return undefined;
  }
  return isAbsolute(workspace) ? workspace : resolve(workspace);
}

function mergePluginsSection(
  config: Record<string, unknown>,
  extensionDir: string,
): { next: Record<string, unknown>; entriesChanged: boolean } {
  const plugins = isRecord(config.plugins) ? { ...config.plugins } : {};

  const allow: unknown[] | undefined = Array.isArray(plugins.allow)
    ? [...(plugins.allow as unknown[])]
    : undefined;
  let allowChanged = false;
  if (allow && !allow.includes(TOKENJUICE_OPENCLAW_PLUGIN_ID)) {
    allow.push(TOKENJUICE_OPENCLAW_PLUGIN_ID);
    allowChanged = true;
  }

  const load = isRecord(plugins.load) ? { ...plugins.load } : {};
  const loadPaths: unknown[] = Array.isArray(load.paths)
    ? [...(load.paths as unknown[])]
    : [];
  let loadPathsChanged = false;
  if (!loadPaths.includes(extensionDir)) {
    loadPaths.push(extensionDir);
    loadPathsChanged = true;
  }

  const entries = isRecord(plugins.entries) ? { ...plugins.entries } : {};
  const existingEntry = isRecord(entries[TOKENJUICE_OPENCLAW_PLUGIN_ID])
    ? { ...(entries[TOKENJUICE_OPENCLAW_PLUGIN_ID] as Record<string, unknown>) }
    : undefined;
  const nextEntry = existingEntry ? { ...existingEntry, enabled: true } : { enabled: true };
  const entryChanged = !existingEntry
    || existingEntry.enabled !== true
    || JSON.stringify(existingEntry) !== JSON.stringify(nextEntry);
  entries[TOKENJUICE_OPENCLAW_PLUGIN_ID] = nextEntry;

  const nextPlugins: Record<string, unknown> = { ...plugins };
  if (allow) {
    nextPlugins.allow = allow;
  }
  nextPlugins.load = { ...load, paths: loadPaths };
  nextPlugins.entries = entries;

  return {
    next: { ...config, plugins: nextPlugins },
    entriesChanged: allowChanged || loadPathsChanged || entryChanged,
  };
}

function removeTokenjuiceFromPluginsSection(
  config: Record<string, unknown>,
  extensionDir: string,
): { next: Record<string, unknown>; removed: number } {
  if (!isRecord(config.plugins)) {
    return { next: config, removed: 0 };
  }
  const plugins = { ...config.plugins };
  let removed = 0;

  if (Array.isArray(plugins.allow)) {
    const allowList = plugins.allow as unknown[];
    const before = allowList.length;
    const nextAllow = allowList.filter((entry) => entry !== TOKENJUICE_OPENCLAW_PLUGIN_ID);
    plugins.allow = nextAllow;
    if (nextAllow.length !== before) {
      removed += 1;
    }
  }

  if (isRecord(plugins.load) && Array.isArray(plugins.load.paths)) {
    const load = { ...plugins.load };
    const paths = load.paths as unknown[];
    const before = paths.length;
    const nextPaths = paths.filter((entry) => entry !== extensionDir);
    load.paths = nextPaths;
    if (nextPaths.length !== before) {
      removed += 1;
    }
    plugins.load = load;
  }

  if (isRecord(plugins.entries) && TOKENJUICE_OPENCLAW_PLUGIN_ID in plugins.entries) {
    const entries = { ...plugins.entries };
    delete entries[TOKENJUICE_OPENCLAW_PLUGIN_ID];
    plugins.entries = entries;
    removed += 1;
  }

  return { next: { ...config, plugins }, removed };
}

async function backupFile(path: string): Promise<string | undefined> {
  if (!(await pathExists(path))) {
    return undefined;
  }
  const backupPath = `${path}.bak-tj-${Date.now()}`;
  await copyFile(path, backupPath);
  return backupPath;
}

async function backupExtensionDir(extensionDir: string): Promise<string | undefined> {
  try {
    const details = await stat(extensionDir);
    if (!details.isDirectory()) {
      return undefined;
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return undefined;
    }
    throw error;
  }
  const backupPath = `${extensionDir}.bak-tj-${Date.now()}`;
  await rename(extensionDir, backupPath);
  return backupPath;
}

async function writeExtensionFiles(
  extensionDir: string,
  runtimeSource: string,
  runtimeConfig: OpenClawExtensionRuntimeConfig,
): Promise<void> {
  await mkdir(extensionDir, { recursive: true });
  const entrySource = buildExtensionEntrySource(runtimeSource, runtimeConfig);
  await writeAtomically(join(extensionDir, "index.js"), entrySource);
  await writeAtomically(join(extensionDir, "package.json"), buildPackageJson());
  await writeAtomically(join(extensionDir, "openclaw.plugin.json"), buildOpenClawPluginManifest());
}

export async function installOpenClawExtension(
  options: OpenClawExtensionCommandOptions = {},
): Promise<InstallOpenClawExtensionResult> {
  const configPath = getOpenClawConfigPath();
  const { data: config } = await readOpenClawConfig(configPath);
  const workspaceDir = getWorkspaceDirFromConfig(config) ?? getDefaultWorkspaceDir();
  const extensionDir = getExtensionDir(workspaceDir);

  const runtimeSource = await loadOpenClawRuntimeSource(Boolean(options.local));
  const extensionBackupPath = await backupExtensionDir(extensionDir);
  await writeExtensionFiles(extensionDir, runtimeSource, options.runtimeConfig ?? {});

  const { next: nextConfig, entriesChanged } = mergePluginsSection(config, extensionDir);
  let configBackupPath: string | undefined;
  let configUpdated = false;
  if (entriesChanged) {
    configBackupPath = await backupFile(configPath);
    await mkdir(dirname(configPath), { recursive: true });
    await writeAtomically(configPath, `${JSON.stringify(nextConfig, null, 2)}\n`);
    configUpdated = true;
  }

  return {
    extensionDir,
    configPath,
    ...(extensionBackupPath ? { extensionBackupPath } : {}),
    ...(configBackupPath ? { configBackupPath } : {}),
    configUpdated,
  };
}

export async function uninstallOpenClawExtension(
  _options: OpenClawExtensionCommandOptions = {},
): Promise<UninstallOpenClawExtensionResult> {
  const configPath = getOpenClawConfigPath();
  const { data: config, existed } = await readOpenClawConfig(configPath);
  const workspaceDir = getWorkspaceDirFromConfig(config) ?? getDefaultWorkspaceDir();
  const extensionDir = getExtensionDir(workspaceDir);

  let removedDir = false;
  if (await pathExists(extensionDir)) {
    await rm(extensionDir, { recursive: true, force: true });
    removedDir = true;
  }

  let removedConfigEntries = 0;
  let configBackupPath: string | undefined;
  if (existed) {
    const { next: nextConfig, removed } = removeTokenjuiceFromPluginsSection(config, extensionDir);
    removedConfigEntries = removed;
    if (removed > 0) {
      configBackupPath = await backupFile(configPath);
      await writeAtomically(configPath, `${JSON.stringify(nextConfig, null, 2)}\n`);
    }
  }

  return {
    extensionDir,
    configPath,
    removedDir,
    removedConfigEntries,
    ...(configBackupPath ? { configBackupPath } : {}),
  };
}

export async function doctorOpenClawExtension(): Promise<OpenClawDoctorReport> {
  const configPath = getOpenClawConfigPath();
  const { data: config } = await readOpenClawConfig(configPath);
  const workspaceDir = getWorkspaceDirFromConfig(config) ?? getDefaultWorkspaceDir();
  const extensionDir = getExtensionDir(workspaceDir);

  const expectedEntryPath = join(extensionDir, "index.js");
  const expectedManifestPath = join(extensionDir, "openclaw.plugin.json");
  const expectedPackagePath = join(extensionDir, "package.json");
  const checkedPaths = [expectedEntryPath, expectedManifestPath, expectedPackagePath];

  const extensionDirExists = await pathExists(extensionDir);
  if (!extensionDirExists) {
    return {
      extensionDir,
      configPath,
      status: "disabled",
      issues: [],
      fixCommand: TOKENJUICE_OPENCLAW_FIX_COMMAND,
      checkedPaths: [],
      missingPaths: [],
    };
  }

  const missingPaths: string[] = [];
  for (const path of checkedPaths) {
    if (!(await pathExists(path))) {
      missingPaths.push(path);
    }
  }

  const issues: string[] = [];
  if (missingPaths.length > 0) {
    issues.push(`tokenjuice openclaw extension is missing required file${missingPaths.length === 1 ? "" : "s"}`);
  }

  let entrySource = "";
  if (await pathExists(expectedEntryPath)) {
    try {
      entrySource = await readFile(expectedEntryPath, "utf8");
    } catch (error) {
      issues.push(`tokenjuice openclaw entry could not be read: ${error instanceof Error ? error.message : String(error)}`);
    }
  }
  if (entrySource && !entrySource.includes("createTokenjuiceOpenClawExtension")) {
    issues.push("installed openclaw extension does not look like a tokenjuice-generated extension");
  }
  if (entrySource && !entrySource.includes("generated by tokenjuice v")) {
    issues.push("installed openclaw extension is missing the tokenjuice generator banner");
  }

  const plugins = isRecord(config.plugins) ? config.plugins : undefined;
  const allowList = plugins && Array.isArray(plugins.allow) ? plugins.allow as unknown[] : undefined;
  const entries = plugins && isRecord(plugins.entries) ? plugins.entries : undefined;
  const entry = entries && isRecord(entries[TOKENJUICE_OPENCLAW_PLUGIN_ID])
    ? entries[TOKENJUICE_OPENCLAW_PLUGIN_ID] as Record<string, unknown>
    : undefined;

  if (allowList && !allowList.includes(TOKENJUICE_OPENCLAW_PLUGIN_ID)) {
    issues.push(
      `${configPath} has a plugins.allow allowlist that does not include "${TOKENJUICE_OPENCLAW_PLUGIN_ID}"; rerun the installer to merge the allowlist entry`,
    );
  }
  if (!entry) {
    issues.push(
      `${configPath} is missing plugins.entries["${TOKENJUICE_OPENCLAW_PLUGIN_ID}"]; rerun the installer to register the plugin`,
    );
  } else if (entry.enabled !== true) {
    issues.push(
      `${configPath} has plugins.entries["${TOKENJUICE_OPENCLAW_PLUGIN_ID}"].enabled !== true; set enabled: true to activate compaction`,
    );
  }

  const loadPaths = plugins && isRecord(plugins.load) && Array.isArray(plugins.load.paths)
    ? plugins.load.paths as unknown[]
    : undefined;
  if (loadPaths && !loadPaths.includes(extensionDir)) {
    issues.push(
      `${configPath} has plugins.load.paths that does not reference ${extensionDir}; rerun the installer to register the load path`,
    );
  }

  const status: OpenClawDoctorReport["status"] = missingPaths.length > 0
    ? "broken"
    : issues.length > 0
      ? "warn"
      : "ok";

  return {
    extensionDir,
    configPath,
    status,
    issues,
    fixCommand: TOKENJUICE_OPENCLAW_FIX_COMMAND,
    checkedPaths,
    missingPaths,
  };
}
